version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:1369 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 1369
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    build: services/postgres
    volumes:
      - ./:/tmp/db
      - postgres_data_prod:/var/lib/postgresql/data/
    ports: ["1368:5432"]
    env_file:
      - ./.env.prod.db
  
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 1369:80
    depends_on:
      - web
volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
